server:
  port: 8080
  servlet:
    context-path: /batch

apiurl: 
  sampleValue: http://localhost:8080/otherservice

  
---
server:
  port: 8083
  
spring:
  profiles: default
  
  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:34.84.76.152:3306}/${DATASORUCE_TABLESPACE:lguplus}
    username: ${DATASORUCE_USERNAME:lguplus}
    password: ${DATASORUCE_PASSWORD:1234}
    driverClassName: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
            
  mybatis:
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true

  quartz:
    job-store-type: jdbc      
    
logging:
  level:
    org:
      hibernate:
        type: trace  
      #springframework:
      #  boot: DEBUG

apiurl: 
  sampleValue: http://localhost:8080/otherservice
    
---
spring:
  profiles: docker
  sleuth:
    sampler:
      probability: 1
    web:
      skipPattern: (^cleanup.*|.+favicon.*)

  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:34.84.76.152:3306}/${DATASORUCE_TABLESPACE:lguplus}
    username: ${DATASORUCE_USERNAME:lguplus}
    password: ${DATASORUCE_PASSWORD:1234}
    driverClassName: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
            
  mybatis:
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true

  quartz:
    job-store-type: jdbc  
        
---
spring:
  profiles: test
  
  datasource:
    url: jdbc:mysql://34.84.76.152:3306/lguplus
    username: lguplus
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  mybatis:
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true

  quartz:
    job-store-type: jdbc        